// DOM-adapter integration tests: no browser or GPU is simulated as a passed visual test.
import fs from 'node:fs';import assert from 'node:assert/strict';import * as T from '../vendor/three.module.js';import {exploration,extendPlaces} from '../src/exploration.js';
const nodes=new Map();function el(id){if(!nodes.has(id))nodes.set(id,{hidden:true,textContent:'',checked:false,value:0,href:'',style:{},appendChild(){},focus(){},addEventListener(){},classList:{add(){},remove(){}},setAttribute(){},showModal(){this.open=true},close(){this.open=false}});return nodes.get(id);}
globalThis.document={getElementById:el,querySelector:()=>null,createElement:()=>({})};globalThis.location={hash:'#v=test'};
const world=JSON.parse(fs.readFileSync('data/world.json')),data=JSON.parse(fs.readFileSync('src/layers-data.json')),src=fs.readFileSync('src/viewer.js','utf8'),places=Function('return '+src.match(/const places=(\[[\s\S]*?\n\]);/)[1])();extendPlaces(places,world,data);
const scene=new T.Scene();scene.fog=new T.FogExp2();scene.add(new T.HemisphereLight());const sky=new T.Object3D();sky.name='Atmospheric sky';sky.material={uniforms:{top:{value:new T.Color()},bottom:{value:new T.Color()},sunStrength:{value:1}}};scene.add(sky);const camera=new T.PerspectiveCamera();camera.position.set(...places[0].fly);const sun=new T.DirectionalLight();let selected=0,season='summer',notice='';
const api=exploration({scene,camera,world,places,data,meshes:[],sun,renderer:{},forest:{season:s=>season=s},reduced:false,jump:i=>selected=i,setMode(){},orient:v=>camera.lookAt(v),toast:t=>notice=t,selected:()=>selected,syncRotation(){}});
el('tour').onclick();for(let i=0;i<80;i++)api.update(.05);assert(api.clock.running);el('tour-pause').onclick();const paused=camera.position.clone();for(let i=0;i<80;i++)api.update(.05);assert(camera.position.equals(paused));el('tour-pause').onclick();assert(api.clock.running);el('tour-next').onclick();api.update(.05);assert.equal(selected,5);el('tour-prev').onclick();api.update(.05);assert.equal(selected,0);el('tour-exit').onclick();assert(!api.clock.running);assert(el('tour-card').hidden);
for(const id of ['layer-labels','layer-routes','layer-rings','layer-boundaries','layer-heights','layer-history']){el(id).onchange({target:{checked:true}});el(id).onchange({target:{checked:false}});}
el('season').onchange({target:{value:'autumn'}});assert.equal(season,'autumn');el('daylight').oninput({target:{value:100}});for(let i=0;i<100;i++)api.update(.05);assert(sun.intensity<.17);assert(sky.material.uniforms.sunStrength.value<.001);el('daylight').oninput({target:{value:0}});for(let i=0;i<100;i++)api.update(.05);assert(sun.intensity>3);
el('building-search').value='Spire';el('find-building').onclick();assert.equal(el('building-name').textContent,'Spire');el('building-search').value='Imaginary Landmark';el('find-building').onclick();assert(el('search-status').textContent.includes('Choose a recorded'));el('roof-view').onclick();assert(Math.abs(camera.position.y-149.2)<.001);assert(notice.includes('Virtual Spire'));el('layers-button').onclick();assert(el('layers-dialog').open);
el('tour').onclick();for(let i=0;i<2400;i++)api.update(.05);assert(api.clock.finished);assert(el('tour-card').hidden);assert.equal(selected,2);
console.log('Interaction logic: all six tour stops, pause/resume, next/previous/exit, layer toggles, day/night, seasons, virtual crown, dialog trigger pass. Browser layout, GPU shaders and real input dispatch are not tested.');
