import fs from 'node:fs';import assert from 'node:assert/strict';import * as T from '../vendor/three.module.js';
import {TourClock,TOUR_ORDER,LEG_SECONDS,HOLD_SECONDS} from '../src/tour.mjs';import {makeRoutes} from '../src/routes.mjs';import {extendPlaces} from '../src/exploration.js';import {makeIndex,safePoint,blocked,pointInBuilding} from '../src/navigation.mjs';
const world=JSON.parse(fs.readFileSync('data/world.json')),data=JSON.parse(fs.readFileSync('src/layers-data.json')),source=fs.readFileSync('src/viewer.js','utf8');const places=Function('return '+source.match(/const places=(\[[\s\S]*?\n\]);/)[1])();extendPlaces(places,world,data);assert.equal(places.length,6);const index=makeIndex(world.buildings);
const clock=new TourClock();clock.start();for(let i=0;i<50;i++)clock.tick(.05);clock.pause();const paused=clock.elapsed;clock.tick(.05);assert.equal(clock.elapsed,paused);clock.resume();clock.tick(.05);assert(clock.elapsed>paused);clock.seek(3);assert.equal(clock.state().place,4);clock.start();const seen=new Set();for(let i=0;i<2400;i++)seen.add(clock.tick(.05).place);assert(clock.finished);assert.deepEqual([...seen],TOUR_ORDER);
const routes=makeRoutes(data.roads,TOUR_ORDER.map(i=>places[i].walk));assert(routes.every(r=>r.available&&r.points.length>1&&r.length>0));
const starts=places.map(p=>{const s=safePoint(...p.walk,index,world.bounds);assert(s);assert(!blocked(...s,1.72,index,.8));return {place:p.name,point:s};});
const samples=[];let from=new T.Vector3(...places[0].fly);for(const i of TOUR_ORDER){const dest=new T.Vector3(...places[i].fly);for(let n=0;n<=180;n++){const t=n/180,u=t*t*t*(t*(t*6-15)+10),p=from.clone().lerp(dest,u);p.y+=Math.sin(Math.PI*u)*320;assert(!blocked(p.x,-p.z,p.y,index,2),'Camera intersects building at '+places[i].name+' '+p.toArray());}samples.push(places[i].name);from=dest;}
const spire=world.buildings.filter(b=>b.id==='8746').sort((a,b)=>b.height-a.height)[0];assert.equal(spire.height,147.2);assert(data.neighborhoods.some(n=>n.name==='CBD'&&pointInBuilding(0,0,n)));
const report={tour:'six destinations; pause/resume/seek/completion pass',cameraPaths:samples,cameraSamples:1086,walkingStarts:starts,routeSegments:routes.map(r=>({metres:Math.round(r.length),points:r.points.length})),totalRouteMetres:Math.round(routes.reduce((n,r)=>n+r.length,0)),spireCrownMetres:spire.height,officialNeighborhoodAtSpire:'CBD',browserRendering:'Not tested: plain-static site has no supported Sites agent-preview server.'};fs.writeFileSync('data/exploration-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
