import * as T from '../vendor/three.module.js';
import {TourClock,TOUR_ORDER} from './tour.mjs';
import {makeRoutes} from './routes.mjs';
import {pointInBuilding} from './navigation.mjs';
const $=id=>document.getElementById(id);
const history=[
 ['Vertical downtown','Spire is a residential tower above a substantial podium. Its stepped roof sections come from city mapping; balcony and facade modules are modeled interpretations.','https://nicholspartnership.com/portfolio/spire'],
 ['1858 → preservation','Larimer Street traces the early commercial city. Larimer Square became Denver’s first designated historic district in 1971. The map does not reconstruct vanished buildings.','https://en.wikipedia.org/wiki/Larimer_Square'],
 ['A changing corridor','The aerial surface records September 2023. It must not be read as a photograph of the completed 16th Street reconstruction. This layer compares source dates, not invented historical geometry.','https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Department-of-Transportation-and-Infrastructure/Programs-Services/Projects/16th-Street-Mall'],
 ['The theater district','Concert halls, theaters and the covered galleria form one connected arts campus. The canopy footprint is mapped; its curved roof and structural rhythm are inferred.','https://www.artscomplex.com/'],
 ['2003 → Dancers','Jonathan Borofsky’s Dancers was installed in 2003. Denver Public Art records its height as 60 feet. The lawn is modeled; the artwork itself is not reproduced.','https://denverpublicart.org/public-arts/dancers/'],
 ['1990 → expansion','The Convention Center opened in 1990 and has expanded since. Roof mapping principally dates to 2022, so this model does not fully represent the later rooftop expansion.','https://en.wikipedia.org/wiki/Colorado_Convention_Center']
];
export function extendPlaces(places,world,data){const [x,y]=data.ccc;world.landmarks['Colorado Convention Center']=[x,y];places.push({id:'convention',name:'Colorado Convention Center',short:'Convention Center',kind:'06 / The convention district',text:'700 14th Street. The expansive exhibition complex southwest of Spire, across 14th Street. Later rooftop additions are not fully captured by the source mapping.',key:'Colorado Convention Center',stats:['2022','roof mapping','700','14th Street'],fly:[220,240,510],target:[x,24,-y],walk:[26,-146],look:[x,15,-y]});places[0].text='Start at 891 14th Street, then discover the theaters, historic blocks and pedestrian corridor around Spire.';places[2].name='16th Street corridor';}
export function exploration(api){
 const {scene,camera,world,places,data,meshes,sun,renderer,forest,reduced}=api;
 const clock=new TourClock();let tourActive=false,from=null,fromQ=null,previousStep=-1,nightTarget=0,night=0,layerHeights=false;
 const rings=new T.Group(),boundaries=new T.Group(),routes=new T.Group();scene.add(rings,boundaries,routes);rings.visible=boundaries.visible=routes.visible=false;
 function line(points,color,parent,y=.8){if(points.length<2)return;const g=new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(p[0],y,-p[1])));const m=new T.Line(g,new T.LineBasicMaterial({color,transparent:true,opacity:.8,depthTest:true}));parent.add(m);}
 [100,250,500,1000].forEach(r=>line(Array.from({length:129},(_,i)=>[Math.cos(i/128*Math.PI*2)*r,Math.sin(i/128*Math.PI*2)*r]),'#75efc4',rings));
 const within=p=>p[0]>=world.bounds[0]&&p[0]<=world.bounds[2]&&p[1]>=world.bounds[1]&&p[1]<=world.bounds[3];
 data.neighborhoods.forEach(n=>n.rings.forEach(r=>{let run=[];for(const p of r){if(within(p))run.push(p);else{line(run,'#d2a6fc',boundaries);run=[];}}line(run,'#d2a6fc',boundaries);}));
 const itinerary=TOUR_ORDER.map(i=>places[i].walk);const routeData=makeRoutes(data.roads,itinerary);routeData.forEach(r=>line(r.points,'#ffcb77',routes,1));
 $('route-length').textContent=routeData.every(r=>r.available)?`${(routeData.reduce((a,r)=>a+r.length,0)/1000).toFixed(2)} km on mapped ways · endpoints snapped to network`:'Some mapped connections are unavailable';
 $('road-date').textContent=data.roadTimestamp.slice(0,10);
 const heightPositions=[],heightColors=[];
 for(const b of world.buildings){const p=b.rings[0];if(p.length<3)continue;const shape=new T.Shape(p.map(v=>new T.Vector2(v[0],v[1])));for(const hole of b.rings.slice(1))shape.holes.push(new T.Path(hole.map(v=>new T.Vector2(v[0],v[1]))));const raw=new T.ShapeGeometry(shape),g=raw.index?raw.toNonIndexed():raw,a=g.attributes.position,color=new T.Color().setHSL(.57-Math.min(b.height,180)/180*.5,.7,.58);for(let i=0;i<a.count;i++){heightPositions.push(a.getX(i),b.height+.25,-a.getY(i));heightColors.push(color.r,color.g,color.b);}g.dispose();if(raw!==g)raw.dispose();}
 const heightGeometry=new T.BufferGeometry();heightGeometry.setAttribute('position',new T.Float32BufferAttribute(heightPositions,3));heightGeometry.setAttribute('color',new T.Float32BufferAttribute(heightColors,3));const heights=new T.Mesh(heightGeometry,new T.MeshBasicMaterial({vertexColors:true,side:T.DoubleSide,transparent:true,opacity:.82}));heights.visible=false;scene.add(heights);
 function refreshStory(){const i=api.selected(),h=history[i];$('history-title').textContent=h[0];$('history-copy').textContent=h[1];$('history-source').href=h[2];$('stop-title').textContent=places[i].name;$('stop-copy').textContent=places[i].text;const xy=world.landmarks[places[i].key];const nb=data.neighborhoods.find(n=>pointInBuilding(...xy,n));$('district-name').textContent=nb?nb.name:'Outside retrieved boundary';}
 function stop(){tourActive=false;clock.pause();$('tour-card').hidden=true;$('tour').classList.remove('active');$('tour').setAttribute('aria-label','Start guided tour');}
 function goStep(){const s=clock.state();from=camera.position.clone();fromQ=camera.quaternion.clone();api.jump(s.place,true);camera.position.copy(from);camera.quaternion.copy(fromQ);previousStep=s.step;refreshStory();$('tour').setAttribute('aria-label','Restart guided tour');$('tour-step').textContent=`${s.step+1} / 6 · ${s.step===0?'Begin at Spire':'Discover downtown'}`;}
 function start(){$('history-card').hidden=true;$('layer-history').checked=false;api.setMode('fly',true);clock.start();tourActive=true;previousStep=-1;from=camera.position.clone();fromQ=camera.quaternion.clone();$('tour-card').hidden=false;$('tour').classList.add('active');$('tour').setAttribute('aria-label','Restart guided tour');$('tour-pause').textContent='Pause';}
 $('tour').onclick=start;$('begin-tour').onclick=()=>{$('welcome').close();start();};$('free-start').onclick=()=>{$('welcome').close();$('view').focus({preventScroll:true});};
 $('tour-pause').onclick=()=>{if(clock.running){clock.pause();$('tour-pause').textContent='Resume';}else{clock.resume();$('tour-pause').textContent='Pause';}};
 $('tour-exit').onclick=()=>{stop();$('view').focus({preventScroll:true});};
 for(const [id,d] of [['tour-next',1],['tour-prev',-1]])$(id).onclick=()=>{clock.seek(clock.state().step+d);previousStep=-1;clock.resume();$('tour-pause').textContent='Pause';};
 $('layers-button').onclick=()=>$('layers-dialog').showModal();
 const names=[...new Set(world.buildings.map(b=>b.id==='8746'?'Spire':b.name))].sort();for(const name of names){const option=document.createElement('option');option.value=name;$('building-options').appendChild(option);}
 $('find-building').onclick=()=>{const query=$('building-search').value.trim().toLowerCase(),matches=world.buildings.filter(b=>(b.id==='8746'?'Spire':b.name).toLowerCase()===query);if(!matches.length){$('search-status').textContent='Choose a recorded name from the suggestions, or click a building in the scene.';return;}stop();api.setMode('fly',true);const b=matches.sort((a,b)=>b.height-a.height)[0],r=b.rings[0],x=r.reduce((s,p)=>s+p[0],0)/r.length,y=r.reduce((s,p)=>s+p[1],0)/r.length;camera.position.set(x,b.height+90,-y);api.orient(new T.Vector3(x+35,b.height*.5,-y));$('building-name').textContent=b.id==='8746'?'Spire':b.name;$('building-info').textContent=`${b.height.toFixed(1)} m highest matched roof section · ${b.source}. Facade detail is approximate.`;$('inspection').style.display='block';$('layers-dialog').close();};
 $('building-search').addEventListener('keydown',e=>{if(e.key==='Enter')$('find-building').click();});

 $('layer-labels').onchange=e=>{$('labels').hidden=!e.target.checked;};
 $('layer-rings').onchange=e=>{rings.visible=e.target.checked;};$('layer-boundaries').onchange=e=>{boundaries.visible=e.target.checked;};$('layer-routes').onchange=e=>{routes.visible=e.target.checked;};$('layer-heights').onchange=e=>{heights.visible=e.target.checked;layerHeights=e.target.checked;$('height-legend').hidden=!layerHeights;};
 $('layer-history').onchange=e=>{if(e.target.checked)stop();$('history-card').hidden=!e.target.checked;refreshStory();};
 $('daylight').oninput=e=>{nightTarget=Number(e.target.value)/100;};$('season').onchange=e=>{forest.season(e.target.value);$('season-note').textContent=e.target.value==='winter'?'Muted winter canopy is illustrative; leaf-off structure is not surveyed.':'Seasonal color is an illustrative atmosphere.';};
 $('roof-view').onclick=()=>{stop();api.setMode('fly',true);const sections=world.buildings.filter(b=>b.id==='8746');const top=sections.sort((a,b)=>b.height-a.height)[0],r=top.rings[0];let p=[r.reduce((a,v)=>a+v[0],0)/r.length,r.reduce((a,v)=>a+v[1],0)/r.length];if(!pointInBuilding(...p,top))p=r[0];camera.position.set(p[0],top.height+2,-p[1]);api.orient(new T.Vector3(-309,15,-331));api.toast('Virtual Spire crown viewpoint · not a public roof or access recommendation.');};
 const hemi=scene.children.find(o=>o.isHemisphereLight),sky=scene.getObjectByName('Atmospheric sky');
 refreshStory();if(!location.hash){let show=true;try{show=!sessionStorage.getItem('denver-intro');sessionStorage.setItem('denver-intro','1');}catch{}if(show)$('welcome').showModal();}
 return {stop,refreshStory,routeData,clock,animating:()=>tourActive&&clock.running||Math.abs(nightTarget-night)>.00001,update(dt){if(tourActive){const s=clock.tick(document.querySelector('dialog[open]')?0:dt);if(s.step!==previousStep)goStep();if(clock.running||s.finished){const t=reduced?1:s.travel,u=t*t*t*(t*(t*6-15)+10),dest=new T.Vector3(...places[s.place].fly),target=new T.Vector3(...places[s.place].target);camera.position.lerpVectors(from,dest,u);camera.position.y+=Math.sin(Math.PI*u)*320;const firstLook=new T.Vector3(0,0,-1).applyQuaternion(fromQ).multiplyScalar(Math.max(100,from.distanceTo(target))).add(from);camera.lookAt(firstLook.lerp(target,u));api.syncRotation();}$('tour-progress').value=s.progress;if(s.finished){stop();api.toast('Tour complete. Choose Walk, a landmark, or a map layer to continue.');}}
 const before=night;night+=(nightTarget-night)*Math.min(1,dt*2.4);if(Math.abs(before-night)>.00001){sun.intensity=3.05*(1-night)+.16*night;sun.color.set('#fff0d1').lerp(new T.Color('#95baff'),night);hemi.intensity=.7*(1-night)+.22*night;scene.environmentIntensity=.7*(1-night)+.16*night;renderer.toneMappingExposure=1.05+night*.12;scene.fog.color.set('#c6d6d9').lerp(new T.Color('#131f39'),night);sky.material.uniforms.sunStrength.value=1-night;sky.material.uniforms.top.value.set('#678ea9').lerp(new T.Color('#071125'),night);sky.material.uniforms.bottom.value.set('#e2e9df').lerp(new T.Color('#29334b'),night);for(const m of meshes){if(/glazing|curtain wall|mullions/.test(m.name)){m.material.emissive.set('#dca568');m.material.emissiveIntensity=night*.16;m.material.envMapIntensity=.8*(1-night)+.08*night;}}}
 }};
}
export function fallback(world,places,reason){
 document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('loading').classList.add('hidden');$('fallback').hidden=false;for(const node of document.body.children){if(node!==$('fallback'))node.inert=true;}$('fallback').focus({preventScroll:true});$('fallback-reason').textContent=reason;$('labels').hidden=true;$('fallback-list').replaceChildren();
 const canvas=$('fallback-map'),c=canvas.getContext('2d'),b=world.bounds,w=canvas.width,h=canvas.height,s=Math.min((w-60)/(b[2]-b[0]),(h-60)/(b[3]-b[1])),off=[(w-(b[2]-b[0])*s)/2,(h-(b[3]-b[1])*s)/2],xy=(x,y)=>[off[0]+(x-b[0])*s,off[1]+(b[3]-y)*s];c.fillStyle='#122631';c.fillRect(0,0,w,h);c.fillStyle='#71919f';for(const p of world.buildings){c.beginPath();for(const r of p.rings){r.forEach(([x,y],i)=>i?c.lineTo(...xy(x,y)):c.moveTo(...xy(x,y)));c.closePath();}c.fill('evenodd');}
 places.forEach((p,i)=>{const pos=world.landmarks[p.key];c.fillStyle='#b5efd2';c.beginPath();c.arc(...xy(...pos),8,0,7);c.fill();c.font='bold 16px system-ui';c.fillStyle='#fff';const pt=xy(...pos);c.fillText(String(i+1),pt[0]+10,pt[1]-8);const li=document.createElement('li');const title=document.createElement('strong');title.textContent=p.name;li.appendChild(title);li.appendChild(document.createTextNode(p.text));$('fallback-list').appendChild(li);});c.fillText('N ↑ · mapped footprints · level terrain',24,30);$('retry-3d').onclick=()=>{const url=new URL(location.href);url.searchParams.delete('view');url.searchParams.set('quality','low');location.assign(url.href);};
}
