import * as T from '../vendor/three.module.js';
export function forest(scene,world){
 let seed=891;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
 const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const c=canvas.getContext('2d');for(let i=0;i<35;i++){c.fillStyle=['#718551','#5c7747','#85965b','#45653f'][i%4];c.beginPath();c.ellipse(random()*128,random()*128,5+random()*10,3+random()*6,random()*6.28,0,6.28);c.fill();}const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;
 const mat=new T.MeshStandardMaterial({map:tex,alphaTest:.35,side:T.DoubleSide,roughness:1});const dummy=new T.Object3D(),normal=new T.Vector3(),v=new T.Vector3(),q=new T.Quaternion();
 const tiers=[112,40,12].map(cards=>{const p=[],uv=[];for(let i=0;i<cards;i++){const a=random()*6.28,k=random()*2-1,r=Math.cbrt(random())*.32;const center=new T.Vector3(Math.cos(a)*Math.sqrt(1-k*k)*r,.69+k*r*.84,Math.sin(a)*Math.sqrt(1-k*k)*r);normal.set(random()-.5,random()-.2,random()-.5).normalize();q.setFromUnitVectors(new T.Vector3(0,0,1),normal);const size=cards===112?.19:cards===40?.29:.42;for(const [x,y,u,w] of [[-1,-1,0,0],[1,-1,1,0],[1,1,1,1],[-1,-1,0,0],[1,1,1,1],[-1,1,0,1]]){v.set(x*size/2,y*size/2,0).applyQuaternion(q).add(center);p.push(v.x,v.y,v.z);uv.push(u,w);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.computeVertexNormals();const m=new T.InstancedMesh(g,mat,world.trees.length);m.frustumCulled=false;m.receiveShadow=true;m.castShadow=cards===112;scene.add(m);return m;});
 const trunks=new T.InstancedMesh(new T.CylinderGeometry(.12,.22,1,5),new T.MeshStandardMaterial({color:'#625442',roughness:1}),world.trees.length);world.trees.forEach(([x,y,h],i)=>{dummy.position.set(x,h*.28,-y);dummy.scale.set(1,h*.56,1);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);});trunks.castShadow=true;trunks.receiveShadow=true;scene.add(trunks);
 return {material:mat,update(camera,quality){const count=[0,0,0];world.trees.forEach(([x,y,h],i)=>{const d=Math.hypot(x-camera.position.x,y+camera.position.z,camera.position.y);const tier=quality==='low'?2:d<210?0:d<600?1:2;dummy.position.set(x,0,-y);dummy.scale.set(h,h,h);dummy.rotation.y=i*2.399963;dummy.updateMatrix();tiers[tier].setMatrixAt(count[tier]++,dummy.matrix);});tiers.forEach((m,i)=>{m.count=count[i];m.instanceMatrix.needsUpdate=true;});},season(s){mat.color.set(s==='autumn'?'#d1a560':s==='winter'?'#a9ada0':'#ffffff');mat.opacity=s==='winter'?.58:1;mat.transparent=s==='winter';mat.needsUpdate=true;}};
}
