import {createAssetLoader,chooseQuality} from './assets.mjs';
import {forest} from './forest.js';
import {extendPlaces,exploration,fallback} from './exploration.js';
import * as THREE from '../vendor/three.module.js';
import {loadRealism,finishMaterial,captureDistrictReflection} from './realism.js';
import {pointInBuilding,makeIndex,blocked,safePoint,localToLonLat} from './navigation.mjs';
const $=id=>document.getElementById(id),world=JSON.parse($('world-data').textContent),index=makeIndex(world.buildings),bounds=world.bounds;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,mobile=matchMedia('(any-pointer: coarse)').matches;
const places=[
 {id:'spire',name:'Spire',short:'Spire',kind:'01 / The center of the scene',text:'891 14th Street. The residential tower at the heart of downtown.',key:'Spire',stats:['147.2 m','modeled crown','41','floors'],fly:[-250,220,320],target:[0,67,0],walk:[-103.92,-60],look:[0,52,0]},
 {id:'larimer',name:'Larimer Square',short:'Larimer Square',kind:'02 / Historic downtown',text:'The historic block on Larimer Street, between 14th and 15th Streets.',key:'Larimer Square',stats:['Historic','district','14th–15th','Larimer Street'],fly:[-545,165,-140],target:[-309,15,-331],walk:[-323,300],look:[-309,4,-350]},
 {id:'mall',name:'16th Street Mall',short:'16th Street',kind:'03 / The pedestrian corridor',text:'The downtown promenade links the civic center with the Union Station end of the district.',key:'16th Street Mall',stats:['16th St','corridor','NW ↔ SE','street direction'],fly:[60,220,50],target:[70,14,-315],walk:[55,275],look:[-35,3,-365]},
 {id:'arts',name:'Performing Arts Complex',short:'Performing Arts',kind:'04 / The arts district',text:'The theaters, concert halls and covered galleria along 14th Street.',key:'Denver Performing Arts Complex',stats:['DCPA','arts complex','14th St','main approach'],fly:[-480,190,280],target:[-235,14,29],walk:[-148,-37],look:[-235,10,29]},
 {id:'park',name:'Sculpture Park',short:'Sculpture Park',kind:'05 / The open-air gathering place',text:'The lawn beside the arts complex, near Speer Boulevard and Cherry Creek.',key:'Sculpture Park',stats:['Open lawn','public space','DCPA','next door'],fly:[-590,125,390],target:[-310,4,166],walk:[-310,-175],look:[-244,10,68]}
];
let features,treesLOD,tourInternal=false,layersData;
let scene,camera,renderer,sun,geometryMeshes=[],labels=[],mode='fly',selected=0,yaw=0,pitch=0,ready=false,last=0,transition=null,touring=false,tourTime=0,frameNo=0,quality=chooseQuality({requested:new URLSearchParams(location.search).get('quality'),coarse:mobile,memory:navigator.deviceMemory,saveData:navigator.connection?.saveData});
const assetBuffers=new Map();let dirty=true,autoQuality=true,slowFrames=0;
const invalidate=()=>{dirty=true;};
const keys=new Set(),stick={x:0,y:0},forward=new THREE.Vector3(),right=new THREE.Vector3(),delta=new THREE.Vector3(),euler=new THREE.Euler(0,0,0,'YXZ'),raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();
const toast=t=>{ $('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3400);};
function progress(t,p){$('load-status').textContent=t;$('load-progress').style.width=p+'%';}
function base64bytes(id){const text=$(id).textContent.trim(),str=atob(text),bytes=new Uint8Array(str.length);for(let i=0;i<str.length;i++)bytes[i]=str.charCodeAt(i);return bytes;}
function canvasTexture(draw,w=256,h=256){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=4;return tex;}
let seed=891;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function facadeTexture(name,color){const glass=/curtain|mullions/.test(name),garage=name.includes('Garage'),brick=name.includes('brick'),spacing=name.includes('SPIRE')?1.42:glass?1.55:garage?5.8:3.4,floor=glass&&!name.includes('SPIRE')?3.65:garage?3.05:3.35;const cols=glass?8:4,rows=8;
 const tex=canvasTexture((c,w,h)=>{// Stored Blender colors are linear; the texture is sRGB.
 const base=new THREE.Color().setRGB(...color);c.fillStyle='#'+base.getHexString();c.fillRect(0,0,w,h);
 const cw=w/cols,ch=h/rows;
 if(brick){c.strokeStyle='#ffffff14';c.lineWidth=.5;for(let y=0;y<h;y+=5){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();for(let x=(y%10?0:5);x<w;x+=11){c.beginPath();c.moveTo(x,y);c.lineTo(x,y+5);c.stroke();}}}
 for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const x=i*cw,y=j*ch,margin=glass?1.1:garage?3:cw*.16,bottom=glass?ch*.12:garage?ch*.35:ch*.23;
 const n=rand();const col=glass?[38+n*17,65+n*22,76+n*26]:[29+n*13,43+n*18,48+n*20];c.fillStyle=`rgb(${col.map(Math.round)})`;c.fillRect(x+margin,y+2,cw-2*margin,ch-bottom-2);
 if(glass){const g=c.createLinearGradient(x,y,x+cw,y+ch);g.addColorStop(0,'#cee8f423');g.addColorStop(.55,'#81a7be12');g.addColorStop(1,'#0c232928');c.fillStyle=g;c.fillRect(x+margin,y+2,cw-margin*2,ch-bottom-2);}
 if(!garage&&n>.76){c.fillStyle=glass?'#c9c4ae55':'#b9aa8655';c.fillRect(x+margin+1,y+3,cw-margin*2-2,ch*(.13+rand()*.31));}
 c.fillStyle='#08131b65';c.fillRect(x+margin,y+2,cw-margin*2,1);c.fillStyle='#e8f1ed36';c.fillRect(x+margin,y+ch-bottom,cw-margin*2,1);
 if(garage){c.fillStyle='#0c151966';for(let r=0;r<5;r++)c.fillRect(x+margin,y+5+r*3,cw-2*margin,1);}
 }
 },512,512);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(1/(spacing*cols),1/(floor*rows));return tex;}
function makeMaterial(g,aerial){const color=new THREE.Color().setRGB(...g.color);const mat=new THREE.MeshStandardMaterial({color,roughness:g.rough,metalness:g.metal,side:THREE.DoubleSide});if(g.aerial){mat.map=aerial;mat.color.setRGB(...g.surface_base);mat.metalness=0;mat.roughness=.94;mat.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>',`#ifdef USE_MAP\nvec4 mapped=texture2D(map,vMapUv);\ndiffuseColor.rgb=mix(diffuseColor.rgb,mapped.rgb,${Number(g.aerial_mix).toFixed(3)});\n#endif`);};mat.customProgramCacheKey=()=>String(g.aerial_mix);}else if(/grid|curtain wall|mullions|Garage/.test(g.name)){mat.map=facadeTexture(g.name,g.color);mat.color.set(0xffffff);mat.roughness=/curtain|mullions/.test(g.name)?.26:.67;mat.metalness=/curtain|mullions/.test(g.name)?.55:.08;}if(g.name.includes('glazing')||g.name.includes('glass canopy')){mat.roughness=.17;mat.metalness=.6;mat.envMapIntensity=1.3;}return finishMaterial(mat,g);}
function sky(){const geo=new THREE.SphereGeometry(8500,32,16);const mat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{sunStrength:{value:1},top:{value:new THREE.Color('#678ea9')},bottom:{value:new THREE.Color('#e2e9df')}},vertexShader:'varying vec3 vWorld;void main(){vec4 p=modelMatrix*vec4(position,1.);vWorld=p.xyz;gl_Position=projectionMatrix*viewMatrix*p;}',fragmentShader:'uniform float sunStrength;uniform vec3 top;uniform vec3 bottom;varying vec3 vWorld;void main(){float h=normalize(vWorld).y;vec3 c=mix(bottom,top,pow(max(h,0.),.43));vec3 sunDir=normalize(vec3(-1.,1.3,1.));float s=pow(max(dot(normalize(vWorld),sunDir),0.),900.);gl_FragColor=vec4(c+vec3(1.,.88,.6)*s*2.*sunStrength,1.);}'});const s=new THREE.Mesh(geo,mat);s.name='Atmospheric sky';scene.add(s);if(quality==='low')return;const envScene=new THREE.Scene();envScene.add(s.clone());const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(envScene,.08,1,12000).texture;pmrem.dispose();}
async function initialize(){progress('Preparing the district…',25);await new Promise(requestAnimationFrame);scene.fog=new THREE.FogExp2('#c6d6d9',.00010);sky();if(quality==='high'){try{const previous=scene.environment;scene.environment=await loadRealism(renderer,JSON.parse(new TextDecoder().decode(assetBuffers.get('realism-data'))));previous?.dispose();}catch(e){toast('Photo materials unavailable; using neutral surfaces.');}assetBuffers.delete('realism-data');}scene.environmentIntensity=.65;scene.add(new THREE.HemisphereLight('#c3d8e5','#776c55',.75));sun=new THREE.DirectionalLight('#fff0d1',3.15);sun.position.set(-700,950,600);sun.castShadow=quality!=='low';sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-1000;sun.shadow.camera.right=1000;sun.shadow.camera.top=1100;sun.shadow.camera.bottom=-1100;sun.shadow.camera.near=100;sun.shadow.camera.far=2600;sun.shadow.bias=-.00015;sun.shadow.normalBias=.08;scene.add(sun,sun.target);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(18000,18000),new THREE.MeshStandardMaterial({color:'#9b9f93',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.32;ground.receiveShadow=true;scene.add(ground);
 const imageURL=URL.createObjectURL(new Blob([assetBuffers.get('aerial-data')],{type:'image/jpeg'}));let aerial;try{aerial=await new THREE.TextureLoader().loadAsync(imageURL);}finally{URL.revokeObjectURL(imageURL);assetBuffers.delete('aerial-data');}aerial.colorSpace=THREE.SRGBColorSpace;aerial.anisotropy=Math.min(quality==='high'?8:2,renderer.capabilities.getMaxAnisotropy());
 progress('Building the street scene…',35);if(!globalThis.DecompressionStream)throw Error('This browser does not support offline geometry decompression. Please use a current version of Chrome, Edge, Firefox or Safari.');const zipped=assetBuffers.get('geometry-data');const raw=await new Response(new Blob([zipped]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();assetBuffers.delete('geometry-data');const dv=new DataView(raw),len=dv.getUint32(0,true),head=JSON.parse(new TextDecoder().decode(new Uint8Array(raw,4,len)));for(const group of head.groups){const arr=new Float32Array(raw,4+len+group.offset,group.count*head.stride),buffer=new THREE.InterleavedBuffer(arr,head.stride),g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.InterleavedBufferAttribute(buffer,3,0));g.setAttribute('normal',new THREE.InterleavedBufferAttribute(buffer,3,3));g.setAttribute('uv',new THREE.InterleavedBufferAttribute(buffer,2,6));if(head.stride>8)g.setAttribute('ambientVisibility',new THREE.InterleavedBufferAttribute(buffer,1,8));else{const ao=new Float32Array(group.count).fill(1);g.setAttribute('ambientVisibility',new THREE.BufferAttribute(ao,1));}if(group.indexCount)g.setIndex(new THREE.BufferAttribute(new Uint32Array(raw,4+len+group.indexOffset,group.indexCount),1));g.computeBoundingSphere();const mesh=new THREE.Mesh(g,makeMaterial(group,aerial));mesh.name=group.name;mesh.castShadow=!group.aerial;mesh.receiveShadow=true;scene.add(mesh);geometryMeshes.push(mesh);if(geometryMeshes.length%4===0)await new Promise(requestAnimationFrame);}
 progress('Planting mapped and inferred trees…',72);await new Promise(requestAnimationFrame);treesLOD=forest(scene,world);treesLOD.update(camera,quality);try{if(quality==='high')captureDistrictReflection(scene,renderer,geometryMeshes);}catch(e){toast('Using sky reflections for this device.');}makeMap();makeLabels();setup();applyQuality(quality);jump(0,true);readHash();features=exploration({scene,camera,world,places,data:layersData,meshes:geometryMeshes,sun,renderer,forest:treesLOD,reduced,jump:(i,instant)=>{tourInternal=true;try{jump(i,instant);}finally{tourInternal=false;}},setMode,orient,toast,selected:()=>selected,syncRotation:()=>{euler.setFromQuaternion(camera.quaternion,'YXZ');yaw=euler.y;pitch=euler.x;}});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;features?.stop();renderer.dispose();fallback(world,places,'The graphics context was lost. The mapped district remains available below.');});ready=true;progress('Ready to explore.',100);setTimeout(()=>$('loading').classList.add('hidden'),120);requestAnimationFrame(loop);}
function orient(target){camera.lookAt(target);euler.setFromQuaternion(camera.quaternion,'YXZ');yaw=euler.y;pitch=euler.x;}
function updateRotation(){pitch=THREE.MathUtils.clamp(pitch,-1.52,1.52);camera.rotation.set(pitch,yaw,0,'YXZ');}
function stopTour(){if(tourInternal)return;features?.stop();touring=false;$('tour').classList.remove('active');$('tour').setAttribute('aria-label','Start an aerial tour');}
function setMode(next,noJump=false){$('view').focus({preventScroll:true});stopTour();transition=null;mode=next;for(const m of ['walk','fly']){$(m).classList.toggle('active',m===mode);$(m).setAttribute('aria-pressed',String(m===mode));}$('altitude').classList.toggle('hidden',mode==='walk');$('mode-hint').innerHTML=mode==='walk'?'<b>Eye level 1.72 m</b> · Shift to walk faster':'<kbd>Q</kbd> / <kbd>E</kbd> lower / rise · <kbd>Shift</kbd> faster';if(!noJump){jump(selected,true);toast(mode==='walk'?'Walking at eye level. Drag to look; use WASD or the joystick to move.':'Free flight. Q / E changes altitude; scroll moves forward.');}}
function jump(i,instant=false){$('view').focus({preventScroll:true});stopTour();selected=i;const p=places[i];$('place-name').textContent=p.name;$('place-kind').textContent=p.kind;$('place-summary').textContent=p.text;['stat-one','stat-one-label','stat-two','stat-two-label'].forEach((id,n)=>$(id).textContent=p.stats[n]);document.querySelectorAll('.place').forEach((b,n)=>b.classList.toggle('active',n===i));$('inspection').style.display='none';if(mode==='walk'){const pt=safePoint(...p.walk,index,bounds);if(pt){transition=null;camera.position.set(pt[0],1.72,-pt[1]);orient(new THREE.Vector3(...p.look));}}else{const pos=new THREE.Vector3(...p.fly),target=new THREE.Vector3(...p.target);if(instant||reduced){transition=null;camera.position.copy(pos);orient(target);}else transition={start:performance.now(),from:camera.position.clone(),to:pos,quat:camera.quaternion.clone(),endquat:new THREE.Quaternion().setFromRotationMatrix(new THREE.Matrix4().lookAt(pos,target,camera.up))};}updateExternal();features?.refreshStory();}
function fullDistrict(){setMode('fly',true);const pos=new THREE.Vector3(-830,1370,1520),target=new THREE.Vector3(40,0,-370);transition={start:performance.now(),from:camera.position.clone(),to:pos,quat:camera.quaternion.clone(),endquat:new THREE.Quaternion().setFromRotationMatrix(new THREE.Matrix4().lookAt(pos,target,camera.up))};toast('Full district: all six landmarks and the connecting blocks.');}
function updateExternal(){if(!camera)return;const [lon,lat]=localToLonLat(camera.position.x,-camera.position.z,world.origin);const heading=(((-yaw*180/Math.PI)%360)+360)%360;const url=new URL('https://www.google.com/maps/@');url.search=new URLSearchParams({api:'1',map_action:'pano',viewpoint:lat.toFixed(7)+','+lon.toFixed(7),heading:heading.toFixed(1),pitch:'0',fov:'80'});$('streetview').href=url.href;$('telemetry').textContent=`${lat.toFixed(5)}° N · ${Math.abs(lon).toFixed(5)}° W · ${Math.round(camera.position.y)} m AGL`;}
let mapBase,mapScale,mapOffset;function makeMap(){mapBase=document.createElement('canvas');mapBase.width=380;mapBase.height=420;const c=mapBase.getContext('2d');c.fillStyle='#192e38';c.fillRect(0,0,380,420);mapScale=Math.min(350/(bounds[2]-bounds[0]),390/(bounds[3]-bounds[1]));mapOffset=[(380-(bounds[2]-bounds[0])*mapScale)/2,(420-(bounds[3]-bounds[1])*mapScale)/2];c.fillStyle='#73909e4a';for(const b of world.buildings){c.beginPath();for(const ring of b.rings){ring.forEach(([x,y],i)=>{let p=mapXY(x,y);if(i===0)c.moveTo(...p);else c.lineTo(...p);});c.closePath();}c.fill('evenodd');}for(let i=0;i<places.length;i++){const xy=world.landmarks[places[i].key],p=mapXY(...xy);c.beginPath();c.arc(...p,7,0,Math.PI*2);c.fillStyle=i===0?'#b5efd2':'#95b2be';c.fill();c.fillStyle='#11262d';c.font='bold 9px system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(String(i+1),p[0],p[1]+.3);}c.strokeStyle='#c2d3d8';c.lineWidth=2;const sx=20,sy=399;c.beginPath();c.moveTo(sx,sy);c.lineTo(sx+500*mapScale,sy);c.stroke();}
function mapXY(x,y){return [mapOffset[0]+(x-bounds[0])*mapScale,mapOffset[1]+(bounds[3]-y)*mapScale];}
function drawMap(){const c=$('map').getContext('2d');c.drawImage(mapBase,0,0);const p=mapXY(camera.position.x,-camera.position.z);c.save();c.translate(...p);c.rotate(-yaw);c.fillStyle='#b5efd233';c.beginPath();c.moveTo(0,0);c.lineTo(-20,-36);c.lineTo(20,-36);c.closePath();c.fill();c.fillStyle='#d4ffe9';c.beginPath();c.moveTo(0,-9);c.lineTo(6,6);c.lineTo(0,3);c.lineTo(-6,6);c.closePath();c.fill();c.restore();}
function makeLabels(){places.forEach((p,i)=>{const el=document.createElement('div');el.className='label'+(i===0?' spire':'');el.textContent=(i+1)+' · '+p.short;$('labels').appendChild(el);const xy=world.landmarks[p.key];labels.push({el,pos:new THREE.Vector3(xy[0],i===0?152:i===3?28:i===5?44:6,-xy[1])});});}
function updateLabels(){const dir=new THREE.Vector3();camera.getWorldDirection(dir);labels.forEach(({el,pos})=>{const v=pos.clone().project(camera);const front=pos.clone().sub(camera.position).dot(dir)>0;const visible=(mode==='fly'||pos.distanceTo(camera.position)<180)&&front&&Math.abs(v.x)<.96&&Math.abs(v.y)<.9;el.style.display=visible?'block':'none';if(visible){el.style.left=((v.x+1)*innerWidth/2)+'px';el.style.top=((1-v.y)*innerHeight/2)+'px';}});}
function inspect(event){mouse.set(event.clientX/innerWidth*2-1,1-event.clientY/innerHeight*2);raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(geometryMeshes,false);if(!hits.length)return;const v=hits[0].point;let candidates=index(v.x,-v.z).filter(b=>pointInBuilding(v.x,-v.z,b));if(!candidates.length)candidates=index(v.x+.3,-v.z+.3).filter(b=>pointInBuilding(v.x+.3,-v.z+.3,b));if(!candidates.length){$('inspection').style.display='none';return;}const b=candidates.sort((a,b)=>Math.abs(a.height-v.y)-Math.abs(b.height-v.y))[0];$('building-name').textContent=b.id==='8746'?'Spire':b.name;$('building-info').textContent=`${b.height.toFixed(1)} m roof section · ${b.source}. Facade detail is approximate.`;$('inspection').style.display='block';}
function move(dt){if(document.querySelector('dialog[open]')){keys.clear();return;}const sprint=keys.has('ShiftLeft')||keys.has('ShiftRight'),speed=mode==='walk'?(sprint?4.4:1.65):(sprint?110:32);let z=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-stick.y,x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stick.x;const up=(keys.has('KeyE')||keys.has('Space')?1:0)-(keys.has('KeyQ')?1:0);if(!z&&!x&&(!up||mode==='walk'))return;stopTour();transition=null;camera.getWorldDirection(forward);if(mode==='walk'){forward.y=0;forward.normalize();}right.crossVectors(forward,camera.up).normalize();delta.copy(forward).multiplyScalar(z).addScaledVector(right,x);if(mode==='fly')delta.y+=up;if(delta.length()>1)delta.normalize();delta.multiplyScalar(speed*dt);const steps=Math.max(1,Math.ceil(delta.length()/.45));delta.divideScalar(steps);for(let s=0;s<steps;s++){const px=camera.position.x+delta.x,py=camera.position.y+delta.y,pz=camera.position.z+delta.z;if(mode==='fly'){camera.position.set(THREE.MathUtils.clamp(px,bounds[0]-1200,bounds[2]+1200),THREE.MathUtils.clamp(py,2,2200),THREE.MathUtils.clamp(pz,-bounds[3]-1200,-bounds[1]+1200));}else{if(px>bounds[0]+1&&px<bounds[2]-1&&!blocked(px,-camera.position.z,1.72,index))camera.position.x=px;if(-pz>bounds[1]+1&&-pz<bounds[3]-1&&!blocked(camera.position.x,-pz,1.72,index))camera.position.z=pz;camera.position.y=1.72;}}}
function applyQuality(q){if(!renderer)return;quality=q;const dpi=q==='low'?Math.min(devicePixelRatio,1):q==='high'?Math.min(devicePixelRatio,1.5):Math.min(devicePixelRatio,1.25);renderer.setPixelRatio(dpi);renderer.shadowMap.enabled=q!=='low';sun.castShadow=q!=='low';renderer.shadowMap.autoUpdate=false;sun.shadow.mapSize.set(q==='high'?2048:1024,q==='high'?2048:1024);if(sun.shadow.map){sun.shadow.map.dispose();sun.shadow.map=null;}renderer.shadowMap.needsUpdate=true;$('quality').value=q;treesLOD?.update(camera,q);invalidate();}
function setSceneOnly(active){document.body.classList.toggle('scene-only',active);$('scene-toggle').setAttribute('aria-pressed',active);$('scene-toggle').setAttribute('aria-label',active?'Show panels':'Hide panels');$('scene-toggle').title=active?'Show panels':'Hide panels';}
function setup(){$('scene-toggle').onclick=()=>{stopTour();setSceneOnly(!document.body.classList.contains('scene-only'));};places.forEach((p,i)=>{const b=document.createElement('button');b.className='place'+(i===0?' active':'');b.innerHTML='<span>'+String(i+1).padStart(2,'0')+'</span>'+p.short;b.onclick=()=>jump(i);$('places').appendChild(b);});for(const m of ['fly','walk'])$(m).onclick=()=>setMode(m);$('overview').onclick=fullDistrict;$('help').onclick=()=>$('help-dialog').showModal();$('share').onclick=()=>$('share-dialog').showModal();document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));$('quality').onchange=e=>{const url=new URL(location.href);url.searchParams.set('quality',e.target.value);location.assign(url.href);};
 const view=$('view');let pointer=null,startX=0,startY=0,totalMove=0;view.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==2)return;view.focus({preventScroll:true});view.setPointerCapture(e.pointerId);pointer=e.pointerId;startX=e.clientX;startY=e.clientY;totalMove=0;stopTour();transition=null;});view.addEventListener('pointermove',e=>{if(pointer!==e.pointerId)return;const dx=e.clientX-startX,dy=e.clientY-startY;totalMove+=Math.abs(dx)+Math.abs(dy);yaw-=dx*.003;pitch-=dy*.003;updateRotation();startX=e.clientX;startY=e.clientY;});view.addEventListener('pointerup',e=>{if(pointer!==e.pointerId)return;pointer=null;if(totalMove<5&&!mobile)inspect(e);});view.addEventListener('pointercancel',()=>pointer=null);view.addEventListener('lostpointercapture',()=>pointer=null);view.addEventListener('contextmenu',e=>e.preventDefault());view.addEventListener('wheel',e=>{e.preventDefault();if(mode!=='fly')return;stopTour();transition=null;camera.getWorldDirection(forward);const dist=THREE.MathUtils.clamp(e.deltaY,-100,100)*-.12;camera.position.addScaledVector(forward,dist);camera.position.y=THREE.MathUtils.clamp(camera.position.y,2,2200);camera.position.x=THREE.MathUtils.clamp(camera.position.x,bounds[0]-1200,bounds[2]+1200);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-bounds[3]-1200,-bounds[1]+1200);},{passive:false});
 addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)&&!['Escape'].includes(e.code))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='KeyR')jump(0);if(e.code==='Escape'){setSceneOnly(false);stopTour();$('inspection').style.display='none';}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();stick.x=stick.y=0;$('stick').firstElementChild.style.transform='';});document.addEventListener('visibilitychange',()=>{keys.clear();stick.x=stick.y=0;last=0;invalidate();});
 const pad=$('stick');let stickPointer=null;const resetStick=()=>{stick.x=stick.y=0;stickPointer=null;pad.firstElementChild.style.transform='';};const updateStick=e=>{const r=pad.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,len=Math.hypot(x,y),s=Math.min(1,35/(len||1));stick.x=x*s/35;stick.y=y*s/35;pad.firstElementChild.style.transform=`translate(${x*s}px,${y*s}px)`;};pad.addEventListener('pointerdown',e=>{e.preventDefault();stickPointer=e.pointerId;pad.setPointerCapture(e.pointerId);updateStick(e);});pad.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)updateStick(e);});pad.addEventListener('pointerup',resetStick);pad.addEventListener('pointercancel',resetStick);pad.addEventListener('lostpointercapture',resetStick);for(const [id,key] of [['rise','KeyE'],['lower','KeyQ']]){$(id).addEventListener('pointerdown',e=>{e.preventDefault();$(id).setPointerCapture(e.pointerId);keys.add(key);});for(const event of ['pointerup','pointercancel','lostpointercapture'])$(id).addEventListener(event,()=>keys.delete(key));}
 $('map').onclick=e=>{const r=$('map').getBoundingClientRect(),x=(e.clientX-r.left)*380/r.width,y=(e.clientY-r.top)*420/r.height;const xx=bounds[0]+(x-mapOffset[0])/mapScale,yy=bounds[3]-(y-mapOffset[1])/mapScale;stopTour();transition=null;if(mode==='walk'){const p=safePoint(xx,yy,index,bounds);if(p)camera.position.set(p[0],1.72,-p[1]);}else camera.position.set(THREE.MathUtils.clamp(xx,bounds[0],bounds[2]),Math.max(camera.position.y,130),-THREE.MathUtils.clamp(yy,bounds[1],bounds[3]));updateExternal();};
 $('streetview').addEventListener('pointerdown',updateExternal);$('copy-link').onclick=async()=>{if(location.protocol==='file:'){toast('Share the downloaded HTML file to open this explorer offline.');$('share-message').textContent='You are viewing an offline file. Send this HTML file to share the explorer.';return;}const url=new URL(location.href);url.hash=`v=${mode},${camera.position.x.toFixed(1)},${camera.position.y.toFixed(2)},${camera.position.z.toFixed(1)},${yaw.toFixed(4)},${pitch.toFixed(4)},${selected}`;try{await navigator.clipboard.writeText(url.href);$('share-message').textContent='View link copied. Website access follows its sharing settings; the downloaded HTML can be sent to anyone.';}catch{$('share-message').textContent=url.href;}};
 $('download').onclick=()=>{if(location.protocol==='file:'){$('share-message').textContent='This file is already the self-contained offline edition. Share the original downloaded file.';return;}const a=document.createElement('a');a.href='offline.html';a.download='Denver_Explorer_Offline.html';a.click();$('share-message').textContent='Downloading the full offline edition (about 31 MB). External photography links still need internet.';};
 addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);invalidate();});
}
function readHash(){if(!location.hash.startsWith('#v='))return;const [m,...s]=location.hash.slice(3).split(','),n=s.map(Number);if(!['walk','fly'].includes(m)||n.length<6||!n.every(Number.isFinite))return;setMode(m,true);selected=THREE.MathUtils.clamp(Math.round(n[5]),0,places.length-1);jump(selected,true);const x=THREE.MathUtils.clamp(n[0],bounds[0]-1200,bounds[2]+1200),z=THREE.MathUtils.clamp(n[2],-bounds[3]-1200,-bounds[1]+1200);if(m==='walk'){const p=safePoint(x,-z,index,bounds);if(p)camera.position.set(p[0],1.72,-p[1]);}else camera.position.set(x,THREE.MathUtils.clamp(n[1],2,2200),z);yaw=n[3];pitch=n[4];updateRotation();}
const previousPosition=new THREE.Vector3(),previousRotation=new THREE.Quaternion();const shadowAnchor=new THREE.Vector3(Infinity,Infinity,Infinity);let previousQuality,previousNight=-1,shadowMode;
function loop(now){
 requestAnimationFrame(loop);if(document.hidden||!ready){last=0;return;}
 const elapsed=last?now-last:0,dt=last?Math.min(elapsed/1000,.05):0;last=now;
 move(dt);
 if(transition){const t=THREE.MathUtils.clamp((now-transition.start)/1500,0,1),u=t*t*(3-2*t);camera.position.lerpVectors(transition.from,transition.to,u);camera.quaternion.slerpQuaternions(transition.quat,transition.endquat,u);euler.setFromQuaternion(camera.quaternion,'YXZ');yaw=euler.y;pitch=euler.x;if(t===1)transition=null;}
 features?.update(dt);
 const moved=previousPosition.distanceToSquared(camera.position)>.000001||1-Math.abs(previousRotation.dot(camera.quaternion))>.0000001;
 const night=Number($('daylight').value);
 if(moved||night!==previousNight||features?.animating())dirty=true;
 if(!dirty)return;
 // Automatic first-session quality reduction is conservative and never increases load.
 if(autoQuality&&frameNo>30&&elapsed>40&&elapsed<250){slowFrames++;if(slowFrames>90&&quality!=='low'){applyQuality('low');autoQuality=false;toast('Light rendering enabled to keep this device responsive.');}}else slowFrames=Math.max(0,slowFrames-1);
 if(moved||quality!==previousQuality){if(frameNo%15===0||quality!==previousQuality)treesLOD?.update(camera,quality);drawMap();updateExternal();updateLabels();if(shadowMode!==mode||shadowAnchor.distanceToSquared(camera.position)>625||quality!==previousQuality){const span=mode==='walk'?180:1150;sun.target.position.set(camera.position.x,0,camera.position.z);sun.position.copy(sun.target.position).add(new THREE.Vector3(-700,950,600));sun.shadow.camera.left=-span;sun.shadow.camera.right=span;sun.shadow.camera.top=span;sun.shadow.camera.bottom=-span;sun.shadow.camera.updateProjectionMatrix();renderer.shadowMap.needsUpdate=true;shadowAnchor.copy(camera.position);shadowMode=mode;}}
 renderer.render(scene,camera);frameNo++;dirty=false;previousPosition.copy(camera.position);previousRotation.copy(camera.quaternion);previousQuality=quality;previousNight=night;
}
// Test graphics before downloading large assets; unsupported devices get the map immediately.
function prepareRenderer(){
 if(!globalThis.DecompressionStream)throw Error('This browser needs a newer version for 3D. The map works below.');
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.12,16000);
 renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:quality==='low'?'low-power':'default',preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='low'?1:1.25));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=quality!=='low';renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;$('view').appendChild(renderer.domElement);
}
const loadFiles=createAssetLoader();
async function assetBytes(id){
 const el=$(id),inline=el.textContent.trim();
 if(inline)return ['realism-data','layers-data'].includes(id)?new TextEncoder().encode(inline):base64bytes(id);
 const paths=JSON.parse(((quality==='low'||id==='aerial-data'&&quality!=='high')&&el.dataset.lightFiles)||el.dataset.files||'[]');
 return loadFiles(paths);
}
async function loadHostedAssets(){
 const ids=['layers-data','geometry-data','aerial-data'];if(quality==='high')ids.push('realism-data');let complete=0;
 await Promise.all(ids.map(async id=>{assetBuffers.set(id,await assetBytes(id));progress('Loading the district…',++complete/ids.length*24);}));
}
async function boot(){
 if(new URLSearchParams(location.search).get('view')==='map'){extendPlaces(places,world,{ccc:[-80.22,-262.37]});fallback(world,places,'Map edition · all six landmarks, without 3D downloads.');return;}
 prepareRenderer();await loadHostedAssets();layersData=JSON.parse(new TextDecoder().decode(assetBuffers.get('layers-data')));assetBuffers.delete('layers-data');extendPlaces(places,world,layersData);await initialize();
}
// UI edits can affect lighting, labels or overlays even when the camera is still.
addEventListener('pageshow',invalidate);
for(const type of ['pointerdown','pointerup','click','input','change','keydown','keyup'])document.addEventListener(type,invalidate,true);
boot().catch(e=>{console.error(e);renderer?.dispose();assetBuffers.clear();if(places.length===5)extendPlaces(places,world,{ccc:[-80.22,-262.37]});fallback(world,places,'The 3D view could not start. '+e.message);});
